### ISSUE TITLE
Query: Ability to run commands on 'mod' for duration of ticket life?

### ISSUE THREAD

**Issue by DraksterAU** [MassiveCraft/MassiveTickets#12]
Would be really cool if mods could:

- Be made invulnerable for the duration of a ticket
- Be Teleported to a player and then back again after ticket is closed
- Have separate inventories and only gain privileges such as /give /gm 1 etc when a ticket is in progress.

Is this possible with MT?

**Comment by ulumulu1510** [comment]
The teleportation to a person is already possible. There is a TP button on every Ticket. Teleporting back however is mot something we offer. There are however a lot of plugins which offer a /back command.

All the other features are not handled within MassiveTickets. Invulnerability and seperate inventories are usually perks Moderators have to their hand anyways and there are a lot of Plugins which already do this.

**Comment by magnusulf** [comment]
Perhaps we should add an option to run specific commands when a ticket is created/picked/finished. That could automate some processes.

**Comment by ulumulu1510** [comment]
Actually you are right Madus:
https://github.com/MassiveCraft/MassiveTickets/blob/master/src/com/massivecraft/massivetickets/entity/MConf.java#L91

You can configure to run commands in these Reactions. The first lines are for the commands the moderator will run on a certain action. This demands that the player is able to run  these commands.

This means you can run a command to set the moderator to gm1 and switch the inventory yourself. Configuration is key.

**Comment by DraksterAU** [comment]
Any way we can have the reactions run as console instead @ulumulu1510?

The idea here is a mod would be a regular player unless they have a ticket to work on.... :/

**Comment by ulumulu1510** [comment]
The third set of lines in a reaction are lines the console will run. The Tag {M} is replaced by the moderators name.

Just be aware that there are multiple endings to a ticket, all ending must contain those ending commands.

**Comment by DraksterAU** [comment]
@ulumulu1510 You are a legend!

Thanks man!
