### ISSUE TITLE
Essentials chat 1.8.1 masivcore v 2.7.5

### ISSUE THREAD

**Issue by sonicwolfsdutch** [MassiveCraft/MassiveTickets#8]
well im looking for a fix but cant find one but the essentials chat for

format: '<{DISPLAYNAME}> {MESSAGE}'

does not work whit factions 2.7.5

if tryed this 

{
    ...
    "chatSetFormat": false,
    ...
    "chatParseTags": true,
    ...    
}

but dint work i get this error

<{factions_relcolor}{factions_relcolor}[Technical]~sonicwolfsdu
tch> test

and {factions_relcolor}{factions_relcolor} is just in white as u can see here

http://gyazo.com/68b57c97a2902acae8d10381c886b8fd

**Comment by oloflarsson** [comment]
This is the MassiveTickets issue tracker. If you still have this issue, please repost at the Factions issue tracker.

**Comment by sonicwolfsdutch** [comment]
no i fixt it a long long long time ago im sorry for forgetting to say its fixed
